### ISSUE TITLE
New "person left with # of autoslays" issue

### ISSUE THREAD

**Issue by Jerpy** [Tommy228/TTTDamagelogs#178] opened 2015-03-30 00:48 UTC
I absolutely love the idea of the feature, but unfortunately it is slightly bugged. If a player gets an autoslay on say.. round 1, gets slain, plays the next few rounds normally, and leaves on round 5, it will still shoot out this message saying they left with an autoslay. This is resulting in quite an amount of false bans on other servers I know of, and for mine I've just made sure to let my team know to ignore it. Hope you get around to fixing this, thanks.

**Comment by Joschasa** [comment] 2015-03-30 07:13
Duplicate of #159 and should be fixed in dev

**Comment by Tommy228** [comment] 2015-03-30 11:34
Yeah, sorry for that. The logs will be updated this week and will include this fix.

**Closed by Tommy228** 2015-03-30 11:34 UTC
Labels: duplicate

**Comment by CSchulz** [comment] 2015-06-30 12:40
Still existing.

**Comment by MrUnknownGamer** [comment] 2015-06-30 22:50
There should be an option to disable this. 

On my server, you must stay the whole round when you are slayin.

**Comment by Linkfan123** [comment] 2015-07-09 13:09
Also, what the heck is up with all the reverts? I don't get it.
Oh, and +1 to the force-stay option.
