### ISSUE TITLE
Found Body and TTT Raido not working

### ISSUE THREAD

**Issue by BuilderGaming** [Tommy228/TTTDamagelogs#129] opened 2015-02-12 01:31 UTC
So I was excited as I was the one to suggest the BodyID but its completely screwed up.

1.) There is already a base for the settings in the TTT Damagelogs. Its called "Body" and is already colored as a light purple. 

2.) TTT Radio does not show the called KOS.

3.) TTT "Found Body" (Which should be renamed to Body as I mentioned" does not working in current rounds. It only works in SOME previous "Old Logs"
![2015-02-11_00016](https://cloud.githubusercontent.com/assets/8619739/6160133/959e97ce-b22c-11e4-9309-618b3e6d64d8.jpg)
![2015-02-11_00017](https://cloud.githubusercontent.com/assets/8619739/6160134/959ea1ce-b22c-11e4-8ddb-47e68b1bccf7.jpg)
As you can see I Iditenfied, and KOS a person on my team and killed the BOT. Yet it never shows up in the Logs.

![2015-02-11_00018](https://cloud.githubusercontent.com/assets/8619739/6160148/ba3fec2c-b22c-11e4-81db-6b78bc39b066.jpg)

This Photo shows the "Found Body" works but does not work as it should. Please fix. Thanks :)

You Got This Tommy :+1: Remember, use the base of Body in the settings tab, don't make another filter system. And if possible just go back and see if you can find the first ever version to be released to have BodyID.

Anyway. You got this, good luck tommy :+1:

**Comment by Joschasa** [comment] 2015-02-12 08:30
> 1.) There is already a base for the settings in the TTT Damagelogs. Its called "Body" and is already colored as a light purple.

There is no "Body"-Color for me. Maybe you were on another Server or use another addition for TTTDamagelogs. You could delete the data/damagelog/colors.txt in your local garrysmod-folder and then connect again to your server to verify.
![nobody](https://cloud.githubusercontent.com/assets/213920/6163996/b8e1d44a-b299-11e4-912f-9db827aae279.png)


> 2.) TTT Radio does not show the called KOS.

Yes, you were right. After i reset my local gmod, i could reproduce this.
It was my fault, i changed the name of the filter only in one of two places. This should be fixed now.

> 3.) TTT "Found Body" does not working in current rounds. It only works in SOME previous "Old Logs"

This feature still works for me, even after my reset.
![workingfilters](https://cloud.githubusercontent.com/assets/213920/6163998/be4116b2-b299-11e4-8112-1af030abe657.png)

**Comment by BuilderGaming** [comment] 2015-02-12 12:07
Hmm. KOS works now but still no BODYID after removing my local data files

**Comment by Joschasa** [comment] 2015-02-12 12:24
Told some other admins to test this feature and it seems to work fine for them. Right now I don't have a clue, what could cause this to fail tbh.

**Comment by Tommy228** [comment] 2015-02-12 16:10
Joschasa actually did a great job, the code looks fine and I also tested it. So I'm closing this for now.

**Closed by Tommy228** 2015-02-12 16:10 UTC

**Comment by comedinha** [comment] 2015-02-12 23:36
Radio not work on my language

**Comment by Joschasa** [comment] 2015-02-13 07:29
The code i used to translate the messages is basically the same code used in gmod itself:
https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/damagelog_events/ttt_radio.lua#L50-L68
https://github.com/garrynewman/garrysmod/blob/2299062c2f7165782b210901dfb4e35965c96408/garrysmod/gamemodes/terrortown/gamemode/cl_voice.lua#L364-L381

Could you be more specific?

**Comment by comedinha** [comment] 2015-02-13 14:23
Wow, i have updated and work, sorry

**Comment by comedinha** [comment] 2015-02-13 14:43
But if use radio with player selected show:
Mister [innocent] used his radio: Yes. [innocent]
