### ISSUE TITLE
Vanishing Weapons

### ISSUE THREAD

**Issue by Lordhallo** [Tommy228/TTTDamagelogs#150] opened 2015-03-16 13:55 UTC
When having the newest Damagelog Version installed the weapon's in an inventory turn invisible after a little while. I checked all Addon's on my server.

**Comment by Tommy228** [comment] 2015-03-16 16:49
Should be fixed in this new gmod update, let me know about that too. If it still isn't fixed I'll have to replace all the NW* stuff with net.

**Comment by Lordhallo** [comment] 2015-03-16 18:44
Fixed

**Comment by HarryTurpin** [comment] 2015-03-16 19:37
I'm still having this issue after update.

**Comment by Tommy228** [comment] 2015-03-18 16:33
I need someone to add me on steam. I can run some tests with *sv_allowcslua* and try to figure it out.

**Comment by HarryTurpin** [comment] 2015-03-18 17:40
http://steamcommunity.com/profiles/76561198041855962/ Feel free.

**Comment by Tommy228** [comment] 2015-03-21 09:20
It seems to be caused by Set/GetNWInt. I replaced them.

**Closed by Tommy228** 2015-03-21 09:20 UTC
Labels: bug, under hard investigation
