### ISSUE TITLE
Round selection out of order

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTTDamagelogs#146] opened 2015-03-14 19:30 UTC
When the rounds exceed more than 10 rounds, they come up as out of order in the round selection under Damagelogs. This is happening on version 2.2.2.

**Comment by Tommy228** [comment] 2015-03-14 21:19
@Joschasa this is related to your changes

**Comment by Joschasa** [comment] 2015-03-14 21:25
Are you sure?
I think this is caused by the gmod update itself: https://github.com/garrynewman/garrysmod/commit/84d8935344021d70d90704f16e6ff42548ca5797?w=1

**Comment by Tommy228** [comment] 2015-03-15 08:13
oh, nvm then

**Comment by Tommy228** [comment] 2015-03-21 10:26
Fixed in exp

**Closed by Tommy228** 2015-03-21 10:26 UTC
Labels: bug
