### ISSUE TITLE
Can't manage reports if joined in the middle of the round

### ISSUE THREAD

**Issue by CyberAP** [Tommy228/TTTDamagelogs#163] opened 2015-03-24 11:25 UTC
If there are some reports before you join the game you won't be able to manage them. Some of them might be shown, but you can't change their state or do force report.
Same thing might happen with logs. You think that you see the current round, but in fact it is a previous one which loads bit by bit as the round continues.
This only happens if you join after the round starts. If you were on a server before the round started this issue never occurs.

**Comment by Tommy228** [comment] 2015-03-29 20:30
I can't reproduce, does it always happen to you?

**Comment by CyberAP** [comment] 2015-03-29 20:52
It happens quite often on my server, but I can't reproduce it locally, because I test with bots.
I can provide you with more info once my server is up, it's moving to another host right now.

**Comment by Tommy228** [comment] 2017-09-03 16:59
Should be fixed on the next version.

**Closed by Tommy228** 2017-09-03 16:59 UTC
Labels: bug
