### ISSUE TITLE
RDM Manager text turns hard to read

### ISSUE THREAD

**Issue by Swagaloo** [Tommy228/TTTDamagelogs#166] opened 2015-03-25 01:09 UTC
When I open the RDM Manager Tab the text is easy to read, but once I click on the report, and then click on another report, the text is hard to see. And it only happens to the last rdm report  you click on. 

It's not really important, but I thought it would be good to bring up.
Sorry if I didn't explain it well, I'll post some screenshots with it.

http://cloud-4.steamusercontent.com/ugc/44248442470535774/8477A1F69FBB218963DCFAE1E96D32162AF97FC5/

I clicked on report 4, then when I click on report 2, report 4 becomes hard to see.

http://cloud-4.steamusercontent.com/ugc/44248442470535880/301268A5DFFF6E578B5EEE32B49DABCE17256732/

**Comment by Tommy228** [comment] 2015-03-25 11:09
This is caused by the latest gmod update.. Robotboy said that it was fixed in the dev branch, so just wait.

**Comment by Tommy228** [comment] 2015-03-25 11:12
nvm, looks like it's a different issue

**Comment by Tommy228** [comment] 2015-03-27 20:36
Can't reproduce, this is probably related to an outdated DLabel.

**Closed by Tommy228** 2015-03-27 20:36 UTC
Labels: bug
